<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<!-- Header: brand, slogan, user bar -->
<header class="pi-header">
    <div class="pi-header-body hidden-xs">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="pi-header-body-phone">
                        <a href="<?php echo Pi::url($this->url('home')); ?>contact" title="تماس با ما">041-32466277</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="pi-header-body-menu">
                        <ul class="list-inline pull-right">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>page/products" title="محصولات">محصولات</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>page/trading" title="بازرگانی">بازرگانی</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>page/work-with-us" title="همکاری با ما">همکاری با ما</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>page/about-us" title="درباره ما">درباره ما</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>contact" title="تماس با ما">تماس با ما</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-header">
                        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                        <?php if ($module == 'system') { ?>
                            <h1>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <img class="img-responsive" src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                                </a>
                            </h1>
                        <?php } else { ?>
                            <h2>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <img class="img-responsive" src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                                </a>
                            </h2>
                        <?php } ?>
                    </div>
                    <div class="navbar-collapse collapse">
                        <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <?php if (!empty($blocks['0'])) { ?>
        <div class="pi-header-slide hidden-xs">
            <div class="pi-zone-0">
                <?php foreach ($blocks['0'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
        </div>
    <?php } else { ?>
        <div class="pi-header-image hidden-xs">
            <img class="img-responsive" src="<?php echo $this->assetTheme('image/header.jpg'); ?>" alt="<?php echo _escape($sitename); ?>">
        </div>
    <?php } ?>
</header>
<!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
<section class="pi-section">
    <?php if ($breadcrumbs) { ?>
        <div class="pi-breadcrumbs">
            <div class="container">
                <div class="row">
                    <?php echo $breadcrumbs; ?>
                </div>
            </div>
        </div>
    <?php } ?>
    <div class="container">
        <div class="pi-main-container">

            <!-- Flash messenger -->
            <?php include $this->template('flash-messenger'); ?>
            <div class="row">
                <!-- Left zone -->
                <?php if (!empty($blocks['1'])) { ?>
                    <div class="pi-zone-1 col-md-4">
                        <?php foreach ($blocks['1'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-md-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-md-8';
                } else {
                    echo 'col-md-12';
                }
                ?>">
                    <!-- Center top zone -->
                    <?php if (isset($blocks['2'])) { ?>
                        <div class="pi-zone-2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-3">
                                <?php
                                if (isset($blocks['3'])) {
                                    foreach ($blocks['3'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-4">
                                <?php
                                if (isset($blocks['4'])) {
                                    foreach ($blocks['4'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Module content starts -->
                    <?php if (!empty($content)) { ?>
                        <div class="<?php echo $module; ?>">
                            <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                <?php echo $content; ?>
                            </div>
                            <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                        </div>
                    <?php } ?>
                    <!-- Module content ends -->
                    <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-5">
                                <?php
                                if (isset($blocks['5'])) {
                                    foreach ($blocks['5'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-6">
                                <?php
                                if (isset($blocks['6'])) {
                                    foreach ($blocks['6'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Center bottom zone -->
                    <?php if (isset($blocks['7'])) { ?>
                        <div class="pi-zone-7">
                            <?php foreach ($blocks['7'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Right zone -->
                <?php if (isset($blocks['8'])) { ?>
                    <div class="col-md-4 pi-zone-8">
                        <?php foreach ($blocks['8'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
            <!-- Bottom foot zone -->
            <?php if (isset($blocks['99'])) { ?>
                <div class="pi-zone-99">
                    <?php foreach ($blocks['99'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</section>
<!-- Footer: sitelink -->
<footer class="pi-footer">
    <div class="pi-footer-social">
        <div class="container">
            <div class="row">
                <div class="col-md-6 pi-footer-social-text">تولید کننده کیسه های پلی پروپیلنی از سال ۱۳۸۱</div>
                <div class="col-md-6 text-right">
                    <ul class="list-inline">
                        <li><a href="#" title=""><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-youtube"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-body">
        <div class="container">
            <div class="row">
                <div class="col-md-2 hidden-xs">
                    <img class="img-responsive text-center" src="<?php echo $this->assetTheme('image/footer-logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                </div>
                <div class="col-md-4">
                    <p>شرکت سام بافت پارسیان تولید کننده کیسه های پلی پروپیلنی در سایز و وزن و رنگهای مختلف فعالیت خود را از سال 1381 در تبریز آغاز نموده است.</p>
                    <p>این شرکت جهت تولید انواع مختلف کیسه های پلی پروپیلنی و جامبو بگ ها از آخرین تکنولوژیها و دستگاههای تولید در راستای افزایش رضایت مشتری استفاه می نماید.</p>
                </div>
                <div class="col-md-4">
                    <h3><a href="<?php echo Pi::url($this->url('home')); ?>page/products" title="محصولات سام بافت">محصولات سام بافت</a></h3>
                    <ul class="list-unstyled">
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>page/bags-of-building-materials" title="کیسه های مخصوص صنایع غذایی و کشاورزی">کیسه های مخصوص صنایع غذایی و کشاورزی</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>page/bags-for-the-food-industry-and-agriculture" title="کیسه های مر بوط به مصالح  ساختمانی">کیسه های مر بوط به مصالح  ساختمانی</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>page/industrial-and-agricultural-bags" title="کیسه های صنعتی و کشاورزی">کیسه های صنعتی و کشاورزی</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>page/accessories-and-other-products" title="تولیدات جانبی و متفرقه">تولیدات جانبی و متفرقه</a></li>
                    </ul>
                </div>
                <div class="col-md-2">
                    <h3><a href="<?php echo Pi::url($this->url('home')); ?>" title="سام بافت">سام بافت</a></h3>
                    <ul class="list-unstyled">
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>page/about-us" title="درباره ما">درباره ما</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>page/work-with-us" title="همکاری با ما">همکاری با ما</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>contact" title="تماس با ما">تماس با ما</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>page/trading" title="بازرگانی">بازرگانی</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6" data-rel="license">تمام حقوق مطالب برای وب سایت <a title="<?php echo _escape($sitename); ?>" href="<?php echo Pi::url($this->url('home')); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="col-md-6 text-right" data-rel="license"> طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>